import Utils from '~/utils';

/* eslint-disable indent */
export default { 'es-ES': [
  ['Mi llegada'],
  ['Welcome bag', 'Tarjeta de transporte, regalo de bienvenida...',
                                                                      1, 1, 1],
  ['Edredón y almohada', 'incluidos durante toda la estancia',             1, 1, 1],
  ['Sábanas desechables', 'Sábanas ajustables, funda de edredón y fundas de almohada para las primeras noches',
                                                                      1, 1, 1],
  ['Sábanas permanentes', 'Sábanas ajustables, funda de edredón y fundas de almohada a lo largo de su estancia',
                                                                  '49€', 1, 1],
  ['Toalla de baño', 'Amplia (150x100cm) para toda su estancia',
                                                                  '15€', 1, 1],
  ['FoodPack', 'Té, zumo, agua, cola, galletas, sopa, arroz, pasta, salsa, sal, compotas, jabón',
                                                                  '49€', 1, 1],
  ['Entrega a domicilio', 'De sus sábanas permanentes, toalla de baño y foodpack',
                                                                  '49€', 1, 1],
  ['Checkin self-service 24/7', 'Recoge sus llaves en el distribuidor de nuestra agencia',
                                                                      1, 1, 1],
  ['Checkin a su domicilio - horarios de apertura', 'De lunes a viernes, de las 9 a las 18 (salvo días feriados)',
                                                                  '79€', 1, 1],
  ['Checkin a su domicilio - 24/7', 'en la tarde, durante la noche, los fines de semana (días feriados incluidos)',
                                                             '149€', '79€', 1],
  ['Seguro de cancelación', 'Reembolso del 80% del Pack (plazo antes del inicio de la reserva)',
                                                     0, '1 mes', '1 semana'],
  ['Servicio de equipaje', 'Viaje manos libres ! Podéis dejar su equipaje en nuestra agencia. (2 piezas de equipaje por un máximo de 10 días)',
                                                                 '129€', 1, 1],
  ['Billetes de transporte x2', 'Válidos para todas las líneas (metro, tranvía, autobús)',
                                                                      0, 1, 1],
  ['Chófer privado', 'Desde el aeropuerto o la estación hasta su nuevo alojamiento',
                                                                      0, 0, 1],
  ['Descubrimiento de su barrio', 'Supermercados, transportes, restaurantes…',
                                                                      0, 0, 1],
  ['Mi archivo'],
  ['Activación de servicios', 'Seguro de vivienda, asistencia, wifi, agua, gas, electricidad…',
                                                                      1, 1, 1],
  ['Contrato individual', 'Incluso para un piso compartido, independiente y flexible',
                                                                      1, 1, 1],
  ['Inventario individual', 'Incluso para un apartamento compartido, independiente y flexible',
                                                                      1, 1, 1],
  ['Mi estancia'],
  ['Asistencia ilimitada', 'Durante toda su estancia',                   1, 1, 1],
  ['Asistencia de emergencia 24/7', 'En caso de emergencia',               1, 1, 1],
  ['Mantenimiento ilimitado', 'Problemas técnicos y fallos',
                                                                      1, 1, 1],
  ['Tiempo de intervención', 'Plazo máximo antes de la primera respuesta',
                                                          '72h', '48h', '48h'],
  ['Asitencia ilimitada para las llaves', 'En caso de pérdida o de robo, le prestaremos llaves durante 2 días.',
                                                                  '49€', 1, 1],
  ['Agente dedicado', 'Soporte personalizado y privilegiado',         0, 0, 1],
  ['Cambio de alojamiento', 'primero cambio de habitación en la misma ciudad (salvo París)',
                                                        '290€', '190€', '90€'],
  ['Cambio de alojamiento en París', 'primero cambio de habitación en París',
                                                       '390€', '290€', '190€'],
  ['Mi salida'],
  ['Checkout en casa', 'Nuestro equipo le acogerá en el apartamento',
                                                                      1, 1, 1],
  ['Checkout 24/7', 'en la tarde, durante la noche, los fines de semana, (salvo días feriados)',
                                                        '149€', '149€', '79€'],
  ['Servicio de equipaje', 'Viaje manos libres ! Podéis dejar su equipaje en nuestra agencia. (2 piezas de equipaje por un máximo de 10 días)',
                                                                 '129€', 1, 1],
  ['Reembolso de la fianza', 'Plazo máximo (salvo en caso de daños en el apartamento)',
                                           '60 días', '40 días', '20 días'],
  ['Fianza (reembolsada al final de su estancia)'],
  Utils.getDepositLine('paris'),
  Utils.getDepositLine('lyon'),
  Utils.getDepositLine('montpellier'),
  Utils.getDepositLine('lille'),
  Utils.getDepositLine('toulouse'),
  ['Pack morada'],
  Utils.getPackLine('paris'),
  Utils.getPackLine('lyon'),
  Utils.getPackLine('montpellier'),
  Utils.getPackLine('lille'),
  Utils.getPackLine('toulouse'),
] };
