export default [
  ['My arrival'],
  ['Welcome Bag', 'Transport map, welcome gifts…',                    1, 1, 1],
  ['Fast check-in', 'Less than 10 minutes',                           1, 1, 1],
  ['Pillow & duvet', 'Provided for your stay',                        1, 1, 1],
  [
    'Sheets, pillow & duvet cases',
    'Brand new. Bed prepared before your arrival',
    'disposable', 1, 1,
  ],
  ['Bath towel', 'Brand new. Delivered at home',                      0, 1, 1],
  [
    'Food pack',
    'Coffee, juice, water, wine, milk, cereals, rice, pasta, sauce. Delivered at home',
    0, 1, 1,
  ],
  ['Booking prioriry', 'Stack the odds in your favor',                0, 1, 1],
  ['Check-in at home', 'Our team waits for you at home',              0, 1, 1],
  ['Check-in 24/7', 'Evenings, nights, weekends, holidays… included', 0, 1, 1],
  [
    'Cancellation insurance',
    '80% refund of the pack (delay before the reservation starts)',
    0, '1 month', '1 week',
  ],
  ['private driver', 'From airport/train station to your home',       0, 0, 1],
  [
    'Neighborhood tour',
    'Supermarkets, transports, restaurants…',
    0, 0, 1,
  ],
  ['Unlimited luggage service', 'Travel hands free',                  0, 0, 1],
  ['My paperwork'],
  [
    'Services activation',
    'Housing insurance, assistance, wifi, water, gas, electricity…',
    1, 1, 1,
  ],
  [
    'Individual lease',
    'Even in a flatshare, independance & flexibility',
    1, 1, 1,
  ],
  [
    'Individual inventory',
    'Even in a flatshare, independance and flexibility',
    1, 1, 1,
  ],
  ['My stay'],
  ['Unlimited assistance', 'During your whole stay',                  1, 1, 1],
  ['24/7 emergency assistance', 'In case of emergency',               1, 1, 1],
  ['Unlimited maintenance', 'Technical issues and breakdowns',        1, 1, 1],
  [
    'Maintenance reactivity',
    'Maximum delay before 1st reply',
    '72h', '48h', '24h',
  ],
  ['Unlimited keys assistance', 'In case of loss or theft, lent keys', 1, 1, 1],
  ['Keys assistance 24/7', 'In case of loss or theft, lent keys',     0, 0, 1],
  ['Dedicated agent', 'Privileged personnalized support',             0, 0, 1],
  [
    'Accommodation switch',
    '1st change of accomodation/room in the same city',
    '290€', '190€', 1,
  ],
  ['My departure'],
  ['Check-out at home', 'Our team meets you at home',                 1, 1, 1],
  ['Checkout 24/7', 'Evenings, nights, weekends, holidays… included', 0, 0, 1],
  ['Unlimited luggage service', 'Travel hands free',                  0, 0, 1],
  [
    'Deposit refund',
    'Maximum delay (except in case of damages)',
    '60 days', '40 days', '20 days',
  ],
  [
    'Non-cashed deposit option',
    'Liberty option: non-cashed French cheque',
    '29€/month', '29€/month', '29€/month',
  ],
];
