export default [
  ['Mon arrivée'],
  ['Sac de Bienvenue', 'carte des transport, cadeau de bienvenue…',                    1, 1, 1],
  ['Checkin rapide', 'moins de 10 minutes',                           1, 1, 1],
  ['Couette & oreiller', 'fourni pour votre séjour',                        1, 1, 1],
  [
    'Draps, oreiller & housse de couette',
    'Neuf. lit préparé à votre arrivée',
    'jetable', 1, 1,
  ],
  ['Serviette de toilette', 'Neuve. livrée à l\'appartment',                      0, 1, 1],
  [
    'Pack de nourriture',
    'Café, jus, eau, vin, lait, céréales, riz, pâtes, sauce. livrée à l\'appartment',
    0, 1, 1,
  ],
  ['Priorité de réservation', 'mettez toute les chances de votre côté',                0, 1, 1],
  ['Checkin au domicile', 'Notre équipe vous attends au domicile',              0, 1, 1],
  ['Checkin 24/7', 'Soirée, nuits, week-ends, vacances… inclus', 0, 1, 1],
  [
    'Assurance annulation',
    '80% du prix du pack logement (délai avant le debut de la réservation)',
    0, '1 mois', '1 semaine',
  ],
  ['chauffeur privé', 'De l\'aéroport/gare à votre domicile',       0, 0, 1],
  [
    'Découverte du quartier',
    'supermarché, transports, restaurants…',
    0, 0, 1,
  ],
  ['Service de bagages', 'voyager les mains libres',                  0, 0, 1],
  ['Mon dossier'],
  [
    'Activation de services',
    'assurance habitation, assistance, wifi, eau, gaz, éléctricité…',
    1, 1, 1,
  ],
  [
    'Bail individuel',
    'Même en collocation, indépendant & fléxible',
    1, 1, 1,
  ],
  [
    'Etat des lieux individuel',
    'Même en collocation, indépendant & fléxible',
    1, 1, 1,
  ],
  ['Mon séjour'],
  ['assistance illimitée', 'Pendant tout votre séjour',                  1, 1, 1],
  ['assistance d\'urgence 24/7', 'En cas d\'urgence',               1, 1, 1],
  ['Interventions illimitées', 'Problèmes techniques et pannes',        1, 1, 1],
  [
    'Réactivité d\'intervention',
    'Délai Maximum après la 1ère réponse',
    '72h', '48h', '24h',
  ],
  ['Assistance clefs illimitée', 'En cas de perte ou vol, clefs de rechange', 1, 1, 1],
  ['Assistance clefs 24/7', 'En cas de perte ou vol, clefs de rechange',     0, 0, 1],
  ['Agent dédié', 'Soutien personnalisé & privilégié',             0, 0, 1],
  [
    'Changement de chambre',
    '1er changement de chambre dans la même ville',
    '290€', '190€', 1,
  ],
  ['Mon Départ'],
  ['Checkout au domicile', 'Notre équipe vous rejoint au domicile',                 1, 1, 1],
  ['Checkout 24/7', 'Soirée, nuits, week-ends, vacances… inclus', 0, 0, 1],
  ['Service de bagages', 'voyager les mains libres',                  0, 0, 1],
  [
    'Remboursement de caution',
    'Délai maximum (sauf dégats dans l\'appartment)',
    '60 jours', '40 jours', '20 jours',
  ],
  [
    'Caution non encaissée',
    'Option liberté: Chèque français non encaissé',
    '29€/mois', '29€/mois', '29€/mois',
  ],
];
