import Utils from '~/utils';

/* eslint-disable indent */
export default { 'es-ES': [
  ['Mi llegada'],
  ['Bolsa de bienvenida', 'Tarjeta de transporte, regalo de bienvenida...',
                                                                      1, 1, 1],
  ['Edredón y almohada', 'Suministrado para su estancia',             1, 1, 1],
  ['Cortinas jetables', 'Sábanas, fundas nórdicas y fundas de almohada por unas noches',
                                                                      1, 1, 1],
  ['Dibujos permanentes', 'Sábanas, fundas nórdicas y fundas de almohada para toda la estancia',
                                                                  '49€', 1, 1],
  ['Toalla', 'Grande (150x100cm) para toda la estancia',
                                                                  '15€', 1, 1],
  ['Paquete de Comida', 'Té, jugo, agua, cola, galletas, sopa, arroz, pasta, salsa, sal, compotas, jabón',
                                                                  '49€', 1, 1],
  ['Entrega a domicilio', 'De tus sábanas permanentes, toalla y comida',
                                                                  '49€', 1, 1],
  ['Check-in self-service 24/7', 'Recoge tus llaves en el distribuidor de nuestra agencia',
                                                                      1, 1, 1],
  ['Checkin en casa - horario de apertura', 'De lunes a viernes, de 9h a 18h (excepto festivos)',
                                                                  '79€', 1, 1],
  ['Checkin en casa - 24/7', 'Noches, noches, fines de semana y festivos incluidos',
                                                             '149€', '79€', 1],
  ['Anulación del seguro', 'Reembolso del 80% del importe del paquete (retraso antes del inicio de la reserva)',
                                                     0, '1 mois', '1 semaine'],
  ['Servicio de equipaje', 'Viaje con las manos libres dejando su equipaje en la agencia (2 maletas para 10 días máximo)',
                                                                 '129€', 1, 1],
  ['Billetes de transporte x2', 'Válido para todas las líneas (metro, tranvía, autobús)',
                                                                      0, 1, 1],
  ['Conductor privado', 'Desde el aeropuerto o estación de tren a su nuevo alojamiento',
                                                                      0, 0, 1],
  ['Descubra su barrio', 'Supermercado, transporte, restaurantes…',
                                                                      0, 0, 1],
  ['Mi archivo'],
  ['Activación de servicios', 'Seguro de hogar, asistencia, wifi, agua, gas, electricidad…',
                                                                      1, 1, 1],
  ['Fianza individual', 'Incluso como apartamento compartido, independiente y flexible',
                                                                      1, 1, 1],
  ['Inventario individual de las instalaciones', 'Incluso como apartamento compartido, independiente y flexible',
                                                                      1, 1, 1],
  ['Mi estancia'],
  ['Soporte ilimitado', 'Durante toda la estancia',                   1, 1, 1],
  ['Ayuda de emergencia 24/7', 'En caso de emergencia',               1, 1, 1],
  ['Mantenimiento ilimitado', 'Problemas técnicos y fallos de funcionamiento',
                                                                      1, 1, 1],
  ['Capacidad de respuesta de la intervención', 'Retardo máximo antes de la 1ª respuesta',
                                                          '72h', '48h', '48h'],
  ['Soporte ilimitado de teclas', 'En caso de pérdida o robo, preste un juego de llaves por 2 días.',
                                                                  '49€', 1, 1],
  ['Agente dedicado', 'Soporte personalizado y privilegiado',         0, 0, 1],
  ['Cambio de alojamiento', '1er cambio de habitación en la misma ciudad (fuera de París)',
                                                        '290€', '190€', '90€'],
  ['Cambio de alojamiento en París', '1er cambio de habitación en París',
                                                       '390€', '290€', '190€'],
  ['Mi partida'],
  ['Check-out en casa', 'Nuestro equipo se reunirá con usted en su casa',
                                                                      1, 1, 1],
  ['Check-out 24/7', 'Noches, noches, fines de semana, festivos incluidos',
                                                        '149€', '149€', '79€'],
  ['Servicio de equipaje', 'Viaje con las manos libres dejando su equipaje en la agencia (2 maletas para 10 días máximo)',
                                                                 '129€', 1, 1],
  ['Reembolso de la garantía', 'Máximo retraso (excepto daños en el apartamento)',
                                           '60 jours', '40 jours', '20 jours'],
  ['Depósito (reembolsado al final de su estancia)'],
  Utils.getDepositLine('paris'),
  Utils.getDepositLine('lyon'),
  Utils.getDepositLine('montpellier'),
  Utils.getDepositLine('lille'),
  Utils.getDepositLine('toulouse'),
  ['Pack morada'],
  Utils.getPackLine('paris'),
  Utils.getPackLine('lyon'),
  Utils.getPackLine('montpellier'),
  Utils.getPackLine('lille'),
  Utils.getPackLine('toulouse'),
] };
