import Utils from '~/utils';

/* eslint-disable indent */
export default { 'fr-FR': [
  ['Mon arrivée'],
  ['Welcome bag', 'Carte des transport, cadeau de bienvenue…',        1, 1, 1],
  ['Couette & oreiller', 'Fournis pour votre séjour',                 1, 1, 1],
  ['Draps jetables', 'Drap housse, housse de couette et taies pour quelques nuits',
                                                                      1, 1, 1],
  ['Draps permanents', 'Drap housse, housse de couette et taies pour tout votre séjour',
                                                                  '49€', 1, 1],
  ['Serviette de bain', 'Large (150x100cm) pour tout votre séjour',
                                                                  '15€', 1, 1],
  ['Pack de nourriture', 'Thé, jus, eau, cola, crackers, soupe, riz, pâtes, sauce, sel, compotes, savon',
                                                                  '49€', 1, 1],
  ['Livraison à domicile', 'De vos draps permanents, serviette et foodpack',
                                                                  '49€', 1, 1],
  ['Check-in self-service 24/7', 'Récupérez vos clefs dans le distributeur à notre agence',
                                                                      1, 1, 1],
  ['Checkin à domicile - heures d\'ouverture', 'Du lundi au vendredi, de 9h à 18h (hors jours fériés)',
                                                                  '79€', 1, 1],
  ['Checkin à domicile - 24/7', 'Soirées, nuits, week-ends et jours fériés inclus',
                                                             '149€', '79€', 1],
  ['Assurance annulation', 'Remboursement de 80% du pack (délai avant le debut de la réservation)',
                                                     0, '1 mois', '1 semaine'],
  ['Service bagagerie', 'Voyagez les mains libres en déposant vos bagages en agence (2 bag. pour 10j max.)',
                                                                 '129€', 1, 1],
  ['Tickets de transports x2', 'Valide pour toutes les lignes (métro, tram, bus)',
                                                                      0, 1, 1],
  ['Chauffeur privé', 'Depuis aéroport ou gare jusqu\'à votre nouveau logement',
                                                                      0, 0, 1],
  ['Découverte de votre quartier', 'Supermarché, transports, restaurants…',
                                                                      0, 0, 1],
  ['Mon dossier'],
  ['Activation de services', 'Assurance habitation, assistance, wifi, eau, gaz, éléctricité…',
                                                                      1, 1, 1],
  ['Bail individuel', 'Même en colocation, indépendant & flexible',  1, 1, 1],
  ['État des lieux individuel', 'Même en colocation, indépendant & flexible',
                                                                      1, 1, 1],
  ['Mon séjour'],
  ['Assistance illimitée', 'Pendant tout votre séjour',               1, 1, 1],
  ['Assistance d\'urgence 24/7', 'En cas d\'urgence',                 1, 1, 1],
  ['Maintenance illimitée', 'Problèmes techniques et pannes',         1, 1, 1],
  ['Réactivité d\'intervention', 'Délai maximum avant la 1ère réponse',
                                                          '72h', '48h', '48h'],
  ['Assistance clefs illimitée', 'En cas de perte ou vol, prêt d\'un jeu de clefs pendant 2 jours',
                                                                  '49€', 1, 1],
  ['Agent dédié', 'Soutien personnalisé & privilégié',                0, 0, 1],
  ['Changement de logement', '1er changement de chambre dans la même ville (hors Paris)',
                                                        '290€', '190€', '90€'],
  ['Changement de logement à Paris', '1er changement de chambre dans Paris',
                                                       '390€', '290€', '190€'],
  ['Mon Départ'],
  ['Check-out à domicile', 'Notre équipe vous rejoint au domicile',   1, 1, 1],
  ['Check-out 24/7', 'Soirées, nuits, week-ends, jours fériés inclus', 0, 0, 1],
  ['Service bagagerie', 'Voyagez les mains libres en déposant vos bagages en agence (2 bag. pour 10j max.)',
                                                                 '129€', 1, 1],
  ['Remboursement de caution', 'Délai maximum (sauf dégats dans l\'appartment)',
                                           '60 jours', '40 jours', '20 jours'],
  ['Caution (remboursée en fin de séjour)'],
  Utils.getDepositLine('paris'),
  Utils.getDepositLine('lyon'),
  Utils.getDepositLine('montpellier'),
  Utils.getDepositLine('lille'),
  Utils.getDepositLine('toulouse'),
  ['Pack logement'],
  Utils.getPackLine('paris'),
  Utils.getPackLine('lyon'),
  Utils.getPackLine('montpellier'),
  Utils.getPackLine('lille'),
  Utils.getPackLine('toulouse'),
] };
