export default {
  Room: {
    'room-features-sleep': {
      sofa: {
        value: false,
        'en-US': 'Sofa',
        'fr-FR': 'Canapé',
        css: 'picto-equipement_chambre_canape_ou_canape_lit',
      },
      duvetAndPillow: {
        value: true,
        'en-US': 'Duvet and Pillow',
        'fr-FR': 'Couette et Oreiller',
        css: 'picto-equipement_chambre_couette_et_oreiller',
      },
      bedsideTable: {
        value: false,
        'en-US': 'Bedside Table',
        'fr-FR': 'Table de chevet',
        css: 'picto-equipement_chambre_table_chevet',
      },
      bedsideLamp: {
        value: false,
        'en-US': 'Bedside Lamp',
        'fr-FR': 'Lampe de chevet',
        css: 'picto-equipement_chambre_table_chevet',
      },
      shutters: {
        value: false,
        'en-US': 'Shutters',
        'fr-FR': 'Volets',
        css: 'picto-equipement_chambre_volets',
      },
      curtains: {
        value: false,
        'en-US': 'Curtains',
        'fr-FR': 'Rideaux',
        css: 'picto-equipement_chambre_rideaux_ou_voilages',
      },
      netCurtains: {
        value: false,
        'en-US': 'Net Curtains',
        'fr-FR': 'Voilage',
        css: 'picto-equipement_chambre_rideaux_ou_voilages',
      },
    },
    'room-features-work': {
      deskAndChair: {
        value: true,
        'en-US': 'Desk and Chair',
        'fr-FR': 'Bureau et Chaise',
        css: 'picto-equipement_chambre_bureau',
      },
      lamp: {
        value: true,
        'en-US': 'Lamp',
        'fr-FR': 'Lampe',
        css: 'picto-equipement_chambre_lampes',
      },
      bookCase: {
        value: false,
        'en-US': 'Book Case',
        'fr-FR': 'Bibliothèque',
        css: 'picto-equipement_chambre_bibliotheque',
      },
      multiSocket: {
        value: true,
        'en-US': 'Multi-Socket Extension Cable',
        'fr-FR': 'Multiprise',
        css: 'picto-equipement_chambre_multiprise',
      },
    },
    'room-features-dress': {
      storage: {
        value: true,
        'en-US': 'Storage',
        'fr-FR': 'Rangements',
        css: 'picto-equipement_chambre_dressing',
      },
      coatHanger: {
        value: false,
        'en-US': ' Coat-hanger',
        'fr-FR': 'Cintres',
        css: 'picto-equipement_chambre_cintres',
      },
      mirror: {
        value: false,
        'en-US': 'Mirror',
        'fr-FR': 'Miroir',
        css: 'picto-equipement_salle_de_bain_miroir',
      },
      walkinWardrobe: {
        value: false,
        'en-US': 'Walk-in Wardrobe',
        'fr-FR': 'Dressing Privé',
        css: 'picto-equipement_chambre_dressing',
      },
    },
    'room-features-general': {
      sofa: {
        value: false,
        'en-US': 'Sofa',
        'fr-FR': 'Canapé',
        css: 'picto-equipement_chambre_canape_ou_canape_lit',
      },
      coffeeTable: {
        value: false,
        'en-US': 'Coffee Table',
        'fr-FR': 'Table Basse',
        css: 'picto-equipement_chambre_table_basse',
      },
      lockedRoom: {
        value: false,
        'en-US': 'Locked Room',
        'fr-FR': 'Chambre fermée à clé',
        css: 'picto-equipement_chambre_fermeture',
      },
      privateBathroom: {
        value: false,
        'en-US': 'Private Bathroom',
        'fr-FR': 'Salle de bain privée',
        css: 'picto-equipement_chambre_sdb_privee',
      },
      privateToilet: {
        value: false,
        'en-US': 'Private Toilet',
        'fr-FR': 'WC Privés',
        css: 'picto-equipement_chambre_wc_prives',
      },
      privateBalcony: {
        value: false,
        'en-US': 'Private Balcony',
        'fr-FR': 'Ballcon privé',
        css: 'picto-equipement_chambre_balcon',
      },
      privateTerrace: {
        value: false,
        'en-US': 'Private Terrace',
        'fr-FR': 'Terrasse Privée',
        css: 'picto-equipement_chambre_balcon',
      },
      privateGarden: {
        value: false,
        'en-US': 'Private Garden',
        'fr-FR': 'Jardin privé',
        css: 'picto-equipement_chambre_jardin',
      },
      balcony: {
        value: false,
        'en-US': 'Balcony',
        'fr-FR': 'Balcon',
        css: 'picto-equipement_chambre_balcon',
      },
      terrace: {
        value: false,
        'en-US': 'Terrace',
        'fr-FR': 'Terrasse',
        css: 'picto-equipement_chambre_balcon',
      },
      garden: {
        value: false,
        'en-US': 'Garden',
        'fr-FR': 'Jardin',
        css: 'picto-equipement_chambre_jardin',
      },
      terraceFurniture: {
        value: false,
        'en-US': 'Terrace Furniture',
        'fr-FR': 'Mobilier de Terrasse',
        css: 'picto-equipement_chambre_mobilier_de_terrasse',
      },
      individualHeating: {
        value: false,
        'en-US': 'Individual Heating',
        'fr-FR': 'Chauffage Individuel',
        css: 'picto-equipement_chambre_mobilier_de_terrasse',
      },
    },
  },
  Apartment: {
    'apartment-features-kitchen': {
      bakingTrays: {
        value: true,
        'en-US': 'Baking Trays',
        'fr-FR': 'Plaques',
        css: 'picto-inclus_gaz',
      },
      oven: {
        value: true,
        'en-US': 'Oven',
        'fr-FR': 'Four',
        css: 'picto-equipement_cuisine_four',
      },
      microwave: {
        value: true,
        'en-US': 'Microwave',
        'fr-FR': 'Micro-onde',
        css: 'picto-equipement_cuisine_micro_ondes',
      },
      dishwasher: {
        value: false,
        'en-US': 'Dishwasher',
        'fr-FR': 'Lave-vaisselle',
        css: 'picto-equipement_cuisine_lave_vaisselle',
      },
      fridge: {
        value: true,
        'en-US': 'Fridge',
        'fr-FR': 'Frigo',
        css: 'picto-equipement_cuisine_frigo',
      },
      kettle: {
        value: true,
        'en-US': 'Kettle',
        'fr-FR': 'Bouilloire',
        css: 'picto-equipement_cuisine_bouilloire',
      },
      pot: {
        value: true,
        'en-US': 'Pot',
        'fr-FR': 'Casseroles',
        css: 'picto-equipement_cuisine_casseroles',
      },
      pan: {
        value: true,
        'en-US': 'Pan',
        'fr-FR': 'Poeles',
        css: 'picto-equipement_cuisine_poeles',
      },
      utensils: {
        value: true,
        'en-US': 'Utensils',
        'fr-FR': 'Ustensiles',
        css: 'picto-equipement_cuisine_ustensiles',
      },
      stewpot: {
        value: true,
        'en-US': 'Stewpot',
        'fr-FR': 'Faitout',
        css: 'picto-equipement_cuisine_ustensiles',
      },
      plates: {
        value: true,
        'en-US': 'Plates',
        'fr-FR': 'Assiettes',
        css: 'picto-equipement_cuisine_assiettes',
      },
      cutlery: {
        value: true,
        'en-US': 'Cutlery',
        'fr-FR': 'Couverts',
        css: 'picto-equipement_cuisine_couverts',
      },
      glasses: {
        value: true,
        'en-US': 'Glasses',
        'fr-FR': 'Verre',
        css: 'picto-equipement_cuisine_verres',
      },
      mugs: {
        value: true,
        'en-US': 'Mugs',
        'fr-FR': 'Mugs',
        css: 'picto-equipement_cuisine_mugs',
      },
      bowls: {
        value: true,
        'en-US': 'Bowls',
        'fr-FR': 'Bols',
        css: 'picto-equipement_cuisine_bols',
      },
      saladBowl: {
        value: true,
        'en-US': 'Salad Bowl',
        'fr-FR': 'Saladier',
        css: 'picto-equipement_cuisine_bols',
      },
      sieve: {
        value: true,
        'en-US': 'Sieve',
        'fr-FR': 'Passoire',
        css: 'picto-equipement_cuisine_bols',
      },
      glassBottle: {
        value: true,
        'en-US': 'Glass Bottle',
        'fr-FR': 'Bouteilles en verre',
        css: 'picto-equipement_cuisine_bouteilles_de_verre',
      },
      scissors: {
        value: true,
        'en-US': 'Scissors',
        'fr-FR': 'Ciseaux',
        css: 'picto-equipement_cuisine_bouteilles_de_verre',
      },
      dryingRack: {
        value: true,
        'en-US': 'Drying Rack',
        'fr-FR': 'Egouttoir',
        css: 'picto-equipement_cuisine_bouteilles_de_verre',
      },
      corkscrew: {
        value: true,
        'en-US': 'Corkscrew',
        'fr-FR': 'Tire-bouchon',
        css: 'picto-equipement_cuisine_tire_bouchon',
      },
      choppingBoards: {
        value: true,
        'en-US': 'Chopping Boards',
        'fr-FR': 'Planches à découper',
        css: 'picto-equipement_general_planche_a_repasser',
      },
      storage: {
        value: true,
        'en-US': 'Storage',
        'fr-FR': 'Rangements',
        css: 'picto-equipement_chambre_rangements',
      },
    },
    'apartment-features-bathroom': {
      bathtub: {
        value: false,
        'en-US': 'Bathtub',
        'fr-FR': 'Baignoire',
        css: 'picto-equipement_salle_de_bain_douche',
      },
      shower: {
        value: false,
        'en-US': 'Shower',
        'fr-FR': 'Douche',
        css: 'picto-equipement_salle_de_bain_douche',
      },
      storage: {
        value: false,
        'en-US': 'Storage',
        'fr-FR': 'Rangements',
        css: 'picto-equipement_chambre_rangements',
      },
      bathMat: {
        value: true,
        'en-US': 'Bath Mat',
        'fr-FR': 'Tapis de Bain',
        css: 'picto-equipement_salle_de_bain_tapis_de_bain',
      },
      mirror: {
        value: true,
        'en-US': 'Mirror',
        'fr-FR': 'Miroir',
        css: 'picto-equipement_salle_de_bain_miroir',
      },
      sink: {
        value: false,
        'en-US': 'Sink',
        'fr-FR': 'Lavabo',
        css: 'picto-equipement_salle_de_bain_douche',
      },
    },
    'apartment-features-general': {
      wifi: {
        value: true,
        'en-US': 'Wifi',
        'fr-FR': 'Wifi',
        css: 'picto-inclus_wifi',
      },
      washingMachine: {
        value: false,
        'en-US': 'Washing Machine',
        'fr-FR': 'Lave-linge',
        css: 'picto-equipement_general_lave_linge',
      },
      storage: {
        value: false,
        'en-US': 'Storage',
        'fr-FR': 'Rangements',
        css: 'picto-equipement_chambre_rangements',
      },
      coatHanger: {
        value: false,
        'en-US': ' Coat-hanger',
        'fr-FR': 'Cintres',
        css: 'picto-equipement_chambre_cintres',
      },
      sofa: {
        value: false,
        'en-US': 'Sofa',
        'fr-FR': 'Canapé',
        css: 'picto-equipement_chambre_canape_ou_canape_lit',
      },
      coffeeTable: {
        value: false,
        'en-US': 'Coffee Table',
        'fr-FR': 'Table Basse',
        css: 'picto-equipement_chambre_table_basse',
      },
      iron: {
        value: true,
        'en-US': 'Iron',
        'fr-FR': 'Fer à repasser',
        css: 'picto-equipement_general_fer_a_repasser',
      },
      ironingBoard: {
        value: true,
        'en-US': 'Ironing Board',
        'fr-FR': 'Planche à repasser',
        css: 'picto-equipement_general_planche_a_repasser',
      },
      dryingRack: {
        value: true,
        'en-US': 'Drying Rack',
        'fr-FR': 'Tancarville',
        css: 'picto-equipement_general_tancarville',
      },
      vaccum: {
        value: true,
        'en-US': 'Vaccum',
        'fr-FR': 'Aspirateur',
        css: 'picto-equipement_general_aspirateur',
      },
      mopAndBucket: {
        value: true,
        'en-US': 'Mop and Bucket',
        'fr-FR': 'Serpillère et seau',
        css: 'picto-equipement_general_kit_menage',
      },
      scrubBrush: {
        value: true,
        'en-US': 'Scrub Brush',
        'fr-FR': 'Balai Brosse',
        css: 'picto-equipement_general_kit_menage',
      },
      balcony: {
        value: false,
        'en-US': 'Balcony',
        'fr-FR': 'Balcon',
        css: 'picto-equipement_chambre_balcon',
      },
      terrace: {
        value: false,
        'en-US': 'Terrace',
        'fr-FR': 'Terrasse',
        css: 'picto-equipement_chambre_balcon',
      },
      garden: {
        value: false,
        'en-US': 'Garden',
        'fr-FR': 'Jardin',
        css: 'picto-equipement_chambre_jardin',
      },
      terraceFurniture: {
        value: false,
        'en-US': 'Terrace Furniture',
        'fr-FR': 'Mobilier de Terrasse',
        css: 'picto-equipement_chambre_mobilier_de_terrasse',
      },
    },
  },
};
